# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://test.com
title: Carolin goes for ...
email: your-email@domain.com
description: > # "Awesome"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
